name: Duplicate Issue on Comment

on:
  issue_comment:
    types: [created]

jobs:
  duplicate-issue:
    if: |
      startsWith(github.event.comment.body, '/duplicate') &&
      (github.event.comment.author_association == 'OWNER' ||
       github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'COLLABORATOR')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download File
        run: |
          curl -o "duplicate-issue.js" https://raw.githubusercontent.com/MorphiaOrg/morphia/refs/heads/master/.github/scripts/duplicate-issue.js
          head -n 40 duplicate-issue.js
        working-directory: ${{ github.workspace }}
      - name: Duplicate Issue Across Milestones
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/duplicate-issue.js');
            await script({github, context, core});