name: Build and Test

on:
  workflow_call:
    inputs:
      java:
        required: false
        type: string
        default: 11
      maven-flags:
        required: false
        type: string
        default: ''

jobs:
  CodeAudits:
    runs-on: ubuntu-latest
    name: Code Audits
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java }}
          distribution: 'zulu'
          server-id: central
          cache: maven

      - name: Find maven
        id: maven
        shell: bash
        run: echo "maven=$( test -f mvnw  && echo "./mvnw" || echo mvn )" >> $GITHUB_OUTPUT

      - name: Run Audits
        run: ${{ steps.maven.outputs.maven }} -U ${{ inputs.maven-flags }} install -Dcode-audits
