name: Build and Test

on:
  workflow_call:
    inputs:
      java:
        required: false
        type: string
        default: 11

jobs:
  CodeAudits:
    uses: ./build.yml@master
    with:
      maven-flags: -U install -Dcode-audits
