name: Pull Requests

on:
  workflow_call:
    inputs:
      java:
        required: false
        type: string
        default: 11
      maven-flags:
        required: false
        type: string
        default: ""

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: ${{ inputs.java }}
      os: ubuntu-latest
      maven-flags: ${{ inputs.maven-flags }}
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    name: Automerge dependabot PRs
    needs:
      - Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
