name: Release

on:
  workflow_call:
    inputs:
      java:
        required: false
        type: string
        default: 11
      maven-flags:
        required: false
        type: string
        default: ''
    secrets:
      GH_PUSH_TOKEN:
        required: true
      MAVEN_GPG_PASSPHRASE:
        required: true
      GPG_PUBLIC_KEY:
        required: true
      GPG_PRIVATE_KEY:
        required: true
      SONATYPE_USERNAME:
        required: true
      SONATYPE_TOKEN:
        required: true

      BLUESKY_USERNAME:
        required: false
      BLUESKY_PASSWORD:
        required: false
      MASTODON_ACCESS_KEY:
        required: false

jobs:
  Release:
    name: Publish Version
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java }}
          distribution: temurin
          cache: maven
          server-id: central
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 4.0.0-rc-5

      - name: Version
        id: vars
        shell: bash
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT

      - name: Publish
        run: |
          mvn ${{ inputs.maven-flags }} --no-transfer-progress -B --file pom.xml \
            -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
            -Drepository.url=https://${{ github.actor }}:${{ secrets.GH_PUSH_TOKEN }}@github.com/${{ github.repository }}.git \
            -Dmaven.site.skip=true -Drelease=true -DskipTests clean deploy
        env:
          SONATYPE_USERNAME       : ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_TOKEN       : ${{ secrets.SONATYPE_TOKEN }}
          MAVEN_GPG_PASSPHRASE    : ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GITHUB_OAUTH            : ${{ secrets.GH_PUSH_TOKEN }}
          JRELEASER_GITHUB_TOKEN: "bob"
          JRELEASER_GPG_PASSPHRASE: "bob"
          JRELEASER_GPG_PUBLIC_KEY: "bob"
          JRELEASER_GPG_SECRET_KEY: "bob"
          JRELEASER_NEXUS2_USERNAME: "bob"
          JRELEASER_NEXUS2_TOKEN: "bob"
          JRELEASER_MAVENCENTRAL_USERNAME: "bob"
          JRELEASER_MAVENCENTRAL_TOKEN: "bob"
