name: Release

on:
  workflow_call:
    inputs:
      java:
        required: false
        type: string
        default: 11
    secrets:
      BLUESKY_PASSWORD:
        required: false
      BLUESKY_USERNAME:
        required: false
      JRELEASER_GITHUB_TOKEN:
        required: true
      JRELEASER_GPG_PASSPHRASE:
        required: true
      JRELEASER_GPG_PUBLIC_KEY:
        required: true
      JRELEASER_GPG_SECRET_KEY:
        required: true
      JRELEASER_NEXUS2_PASSWORD:
        required: true
      JRELEASER_NEXUS2_USERNAME:
        required: true
      MASTODON_ACCESS_KEY:
        required: false

jobs:
  Release:
    name: Publish Version
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache maven artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            **/target
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java }}
          distribution: 'temurin'
          server-id: central
          server-username: JRELEASER_NEXUS2_USERNAME
          server-password: JRELEASER_NEXUS2_PASSWORD
          gpg-private-key: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          gpg-passphrase: JRELEASER_GPG_PASSPHRASE

      - name: Version
        id: vars
        shell: bash
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT

      - name: Check for snapshot
        id: release
        shell: bash
        run: |
          echo "MVN_RELEASE=${{ endsWith( steps.vars.outputs.VERSION, '-SNAPSHOT' ) }} " >> $GITHUB_OUTPUT

      - name: Publish
        run: mvn -e -Drelease deploy jreleaser:full-release -Dsnapshot.build=${{ steps.release.outputs.MVN_RELEASE }}
        env:
          BLUESKY_PASSWORD: ${{secrets.BLUESKY_PASSWORD }}
          BLUESKY_USERNAME: ${{secrets.BLUESKY_USERNAME }}
          JRELEASER_GITHUB_TOKEN: ${{secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_NEXUS2_PASSWORD: ${{secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_NEXUS2_USERNAME: ${{secrets.JRELEASER_NEXUS2_USERNAME }}
          MASTODON_ACCESS_KEY: ${{secrets.MASTODON_ACCESS_KEY }}

      - name: collect logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: "jreleaser-trace.log"
          path: target/jreleaser/trace.log
