name: Release

on:
  workflow_call:
    inputs:
      java:
        required: false
        type: string
        default: 11
      maven-flags:
        required: false
        type: string
        default: ''
    secrets:
      GH_PUSH_TOKEN:
        required: true
      MAVEN_GPG_PASSPHRASE:
        required: true
      GPG_PUBLIC_KEY:
        required: true
      GPG_PRIVATE_KEY:
        required: true
      SONATYPE_USERNAME:
        required: true
      SONATYPE_TOKEN:
        required: true

      BLUESKY_USERNAME:
        required: false
      BLUESKY_PASSWORD:
        required: false
      MASTODON_ACCESS_KEY:
        required: false

jobs:
  Publish:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java }}
          distribution: temurin
          cache: maven
          server-id: central
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 4.0.0-rc-5

      - name: Publish
        run: |
          mvn -U -Ppublication help:effective-pom
          mvn -U -Ppublication help:active-profiles
          mvn -U deploy -Ppublication -DskipTests -Ddeploy.skip=true -Dinvoker.skip=true -N
        env:
          SONATYPE_USERNAME   : ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_TOKEN      : ${{ secrets.SONATYPE_TOKEN }}
          MAVEN_GPG_PASSPHRASE      : ${{ secrets.MAVEN_GPG_PASSPHRASE }}
#          GITHUB_OAUTH        : ${{ secrets.GH_PUSH_TOKEN }}